language: generic

sudo: required
services:
    - docker

before-install:
    - docker build -t benchaw/docker-react -f Dockerfile.dev .

script:
    - docker run USERNAME/docker-react npm run test -- --coverage
    


