language: generic

sudo: required
services:
    - docker

before-install:
    - docker build -t bentchaw/docker-react -f Dockerfile.dev .

script:
    - docker run bentchaw/docker-react npm run test -- --coverage

install: travis_wait 30 mvn install

install: travis_wait 30 mvn install
