language: generic

sudo: required
services:
    - docker

before-install:
    - docker build -t bentchaw/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bentchaw/docker-react npm run test
